create database Smart_club
GO
use Smart_club
DROP TABLE IF EXISTS Events;
DROP TABLE IF EXISTS Reviews;
DROP TABLE IF EXISTS Activities;
DROP TABLE IF EXISTS Team;
DROP TABLE IF EXISTS Match;
DROP TABLE IF EXISTS Activities_Reviewes;
DROP TABLE IF EXISTS Events_Reviews;


CREATE TABLE Events (
Event_id INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
Name VARCHAR (55) NOT NULL,
Place VARCHAR (70),
Date DATE NOT NULL,
Likes INT DEFAULT 0 NOT NULL,
Fees INT NOT NULL);

CREATE TABLE Reviews (
Review_id INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
Comment TEXT,
Rating INT NOT NULL,
Date DATE NOT NULL);

CREATE TABLE Activities (
Activity_id INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
Name VARCHAR (55) NOT NULL,
Place VARCHAR (100) NOT NULL,
Likes INT DEFAULT 0 NOT NULL,
Trainer_ssn INT NOT NULL);

CREATE TABLE Team (
Team_id INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
Size INT NOT NULL,
Training_time DATE NOT NULL);

CREATE TABLE Match (
Match_id INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
Team_id INT NOT NULL,
Time DATE NOT NULL,
Place VARCHAR (100) NOT NULL);

CREATE TABLE Activities_Reviewes (
Review_id INT NOT NULL,
Activity_id INT NOT NULL,
Member_id INT NOT NULL);

CREATE TABLE Events_Reviews (
Review_id INT NOT NULL,
Event_id INT NOT NULL,
Member_id INT NOT NULL);

ALTER TABLE Match ADD FOREIGN KEY (Team_id) REFERENCES Team(Team_id) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE Activities_Reviewes ADD FOREIGN KEY (Review_id) REFERENCES Reviews(Review_id) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE Activities_Reviewes ADD FOREIGN KEY (Activity_id) REFERENCES Activities(Activity_id) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE Events_Reviews ADD FOREIGN KEY (Review_id) REFERENCES Reviews(Review_id) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE Events_Reviews ADD FOREIGN KEY (Event_id) REFERENCES Events(Event_id) ON DELETE CASCADE ON UPDATE CASCADE;